=begin
#IONOS DBaaS REST API

#An enterprise-grade Database is provided as a Service (DBaaS) solution that can be managed through a browser-based \"Data Center Designer\" (DCD) tool or via an easy to use API.  The API allows you to create additional database clusters or modify existing ones. It is designed to allow users to leverage the same power and flexibility found within the DCD visual tool. Both tools are consistent with their concepts and lend well to making the experience smooth and intuitive. 

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.2.1-SNAPSHOT

=end

# Common files
require 'ionoscloud-dbaas-postgres/api_client'
require 'ionoscloud-dbaas-postgres/api_error'
require 'ionoscloud-dbaas-postgres/version'
require 'ionoscloud-dbaas-postgres/configuration'

# Models
require 'ionoscloud-dbaas-postgres/models/api_version'
require 'ionoscloud-dbaas-postgres/models/backup_metadata'
require 'ionoscloud-dbaas-postgres/models/backup_response'
require 'ionoscloud-dbaas-postgres/models/cluster_backup'
require 'ionoscloud-dbaas-postgres/models/cluster_backup_list'
require 'ionoscloud-dbaas-postgres/models/cluster_backup_list_all_of'
require 'ionoscloud-dbaas-postgres/models/cluster_list'
require 'ionoscloud-dbaas-postgres/models/cluster_list_all_of'
require 'ionoscloud-dbaas-postgres/models/cluster_logs'
require 'ionoscloud-dbaas-postgres/models/cluster_logs_instances'
require 'ionoscloud-dbaas-postgres/models/cluster_logs_messages'
require 'ionoscloud-dbaas-postgres/models/cluster_properties'
require 'ionoscloud-dbaas-postgres/models/cluster_response'
require 'ionoscloud-dbaas-postgres/models/connection'
require 'ionoscloud-dbaas-postgres/models/create_cluster_properties'
require 'ionoscloud-dbaas-postgres/models/create_cluster_request'
require 'ionoscloud-dbaas-postgres/models/create_restore_request'
require 'ionoscloud-dbaas-postgres/models/db_user'
require 'ionoscloud-dbaas-postgres/models/day_of_the_week'
require 'ionoscloud-dbaas-postgres/models/error_message'
require 'ionoscloud-dbaas-postgres/models/error_response'
require 'ionoscloud-dbaas-postgres/models/maintenance_window'
require 'ionoscloud-dbaas-postgres/models/metadata'
require 'ionoscloud-dbaas-postgres/models/pagination'
require 'ionoscloud-dbaas-postgres/models/pagination_links'
require 'ionoscloud-dbaas-postgres/models/patch_cluster_properties'
require 'ionoscloud-dbaas-postgres/models/patch_cluster_request'
require 'ionoscloud-dbaas-postgres/models/postgres_version_list'
require 'ionoscloud-dbaas-postgres/models/postgres_version_list_data'
require 'ionoscloud-dbaas-postgres/models/resource_type'
require 'ionoscloud-dbaas-postgres/models/state'
require 'ionoscloud-dbaas-postgres/models/storage_type'
require 'ionoscloud-dbaas-postgres/models/synchronization_mode'

# APIs
require 'ionoscloud-dbaas-postgres/api/backups_api'
require 'ionoscloud-dbaas-postgres/api/clusters_api'
require 'ionoscloud-dbaas-postgres/api/logs_api'
require 'ionoscloud-dbaas-postgres/api/metadata_api'
require 'ionoscloud-dbaas-postgres/api/restores_api'

module IonoscloudDbaasPostgres
  class << self
    # Customize default settings for the SDK using block.
    #   IonoscloudDbaasPostgres.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
